wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.10
    framework: huggingface
    huggingface_version: 4.33.2
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1697984911.900023
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      - 71
      - 77
      - 103
      3:
      - 13
      - 23
      4: 3.11.4
      5: 0.15.10
      6: 4.33.2
      8:
      - 1
      - 2
      - 5
