out_dir: tests/results
dataset:
  format: PyG-MalNetLarge
  name: LocalDegreeProfile
  task: graph
  task_type: classification
  transductive: False
train:
  mode: custom_finetune
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
  sampler: full_batch
model:
  type: gnn
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: add
gnn:
  layers_pre_mp: 1
  layers_mp: 2
  layers_post_mp: 1
  dim_inner: 300
  layer_type: sageconv
  stage_type: stack
  batchnorm: True
  act: prelu
  dropout: 0.0
  agg: mean
  normalize_adj: False
optim:
  batch_accumulation: 4
  optimizer: adam
  base_lr: 0.01
  max_epoch: 100