wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.10
    framework: huggingface
    huggingface_version: 4.33.2
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1697985080.376204
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      - 71
      - 77
      - 103
      2:
      - 1
      - 2
      - 3
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      - 71
      - 77
      - 103
      3:
      - 13
      - 23
      4: 3.11.4
      5: 0.15.10
      6: 4.33.2
      8:
      - 1
      - 2
      - 5
print:
  desc: null
  value: both
accelerator:
  desc: null
  value: cuda
devices:
  desc: null
  value: 1
out_dir:
  desc: null
  value: results_{source}_{search}_Sun_22_Oct_14_30
cfg_dest:
  desc: null
  value: config.yaml
custom_metrics:
  desc: null
  value: []
seed:
  desc: null
  value: 0
round:
  desc: null
  value: 5
tensorboard_each_run:
  desc: null
  value: false
tensorboard_agg:
  desc: null
  value: true
num_workers:
  desc: null
  value: 0
num_threads:
  desc: null
  value: 6
metric_best:
  desc: null
  value: auto
metric_agg:
  desc: null
  value: argmax
view_emb:
  desc: null
  value: false
gpu_mem:
  desc: null
  value: false
benchmark:
  desc: null
  value: false
share:
  desc: null
  value:
    dim_in: 1
    dim_out: 1
    num_splits: 3
dataset:
  desc: null
  value:
    name: TPUGraphs
    format: PyG-TPUGraphs
    dir: ./datasets
    task: graph
    task_type: ranking
    transductive: false
    split:
    - 0.8
    - 0.1
    - 0.1
    shuffle_split: true
    split_mode: standard
    encoder: true
    encoder_name: db
    encoder_bn: true
    node_encoder: false
    node_encoder_name: Atom
    node_encoder_bn: true
    edge_encoder: false
    edge_encoder_name: Bond
    edge_encoder_bn: true
    encoder_dim: 128
    edge_dim: 128
    edge_train_mode: all
    edge_message_ratio: 0.8
    edge_negative_sampling_ratio: 1.0
    resample_disjoint: false
    resample_negative: false
    transform: none
    cache_save: false
    cache_load: false
    remove_feature: false
    tu_simple: true
    to_undirected: false
    location: local
    label_table: none
    label_column: none
    split_index: 0
    split_dir: ./splits
    node_encoder_num_types: 0
    edge_encoder_num_types: 0
    slic_compactness: 10
train:
  desc: null
  value:
    batch_size: 32
    sampler: full_batch
    sample_node: false
    node_per_graph: 32
    radius: extend
    eval_period: 1
    skip_train_eval: false
    ckpt_period: 100
    enable_ckpt: true
    auto_resume: false
    epoch_resume: -1
    ckpt_clean: true
    iter_per_epoch: 32
    walk_length: 4
    neighbor_sizes:
    - 20
    - 15
    - 10
    - 5
    mode: custom_tpu
    num_sample_config: 64
    ckpt_best: false
val:
  desc: null
  value:
    sample_node: false
    sampler: full_batch
    node_per_graph: 32
    radius: extend
model:
  desc: null
  value:
    type: custom_tpu_gnn
    match_upper: true
    loss_fun: cross_entropy
    size_average: mean
    thresh: 0.5
    edge_decoding: dot
    graph_pooling: add
gnn:
  desc: null
  value:
    head: graph
    layers_pre_mp: 0
    layers_mp: 4
    layers_post_mp: 3
    dim_inner: 256
    layer_type: sageconv
    stage_type: skipsum
    skip_every: 1
    batchnorm: false
    act: prelu
    dropout: 0.1
    agg: mean
    normalize_adj: false
    msg_direction: single
    self_msg: concat
    att_heads: 1
    att_final_linear: false
    att_final_linear_bn: false
    l2norm: true
    keep_edge: 0.5
    clear_feature: true
    dim_in: 128
    residual: false
optim:
  desc: null
  value:
    optimizer: adam
    base_lr: 0.0001
    weight_decay: 0.0005
    momentum: 0.9
    scheduler: cos
    steps:
    - 30
    - 60
    - 90
    lr_decay: 0.1
    max_epoch: 2000
    batch_accumulation: 1
    reduce_factor: 0.1
    schedule_patience: 10
    min_lr: 0.0
    num_warmup_epochs: 50
    clip_grad_norm: false
bn:
  desc: null
  value:
    eps: 1.0e-05
    mom: 0.1
mem:
  desc: null
  value:
    inplace: false
example_arg:
  desc: null
  value: example
example_group:
  desc: null
  value:
    example_arg: example
device:
  desc: null
  value: cuda
source:
  desc: null
  value: nlp
search:
  desc: null
  value: random
posenc_LapPE:
  desc: null
  value:
    enable: false
    model: none
    dim_pe: 16
    layers: 3
    n_heads: 4
    post_layers: 0
    raw_norm_type: none
    pass_as_var: false
    eigen:
      laplacian_norm: sym
      eigvec_norm: L2
      max_freqs: 10
posenc_SignNet:
  desc: null
  value:
    enable: false
    model: none
    dim_pe: 16
    layers: 3
    n_heads: 4
    post_layers: 0
    raw_norm_type: none
    pass_as_var: false
    eigen:
      laplacian_norm: sym
      eigvec_norm: L2
      max_freqs: 10
    phi_out_dim: 4
    phi_hidden_dim: 64
posenc_RWSE:
  desc: null
  value:
    enable: false
    model: none
    dim_pe: 16
    layers: 3
    n_heads: 4
    post_layers: 0
    raw_norm_type: none
    pass_as_var: false
    kernel:
      times: []
      times_func: ''
posenc_HKdiagSE:
  desc: null
  value:
    enable: false
    model: none
    dim_pe: 16
    layers: 3
    n_heads: 4
    post_layers: 0
    raw_norm_type: none
    pass_as_var: false
    kernel:
      times: []
      times_func: ''
posenc_ElstaticSE:
  desc: null
  value:
    enable: false
    model: none
    dim_pe: 16
    layers: 3
    n_heads: 4
    post_layers: 0
    raw_norm_type: none
    pass_as_var: false
    kernel:
      times: []
      times_func: range(10)
posenc_EquivStableLapPE:
  desc: null
  value:
    enable: false
    raw_norm_type: none
    eigen:
      laplacian_norm: sym
      eigvec_norm: L2
      max_freqs: 10
name_tag:
  desc: null
  value: ''
pretrained:
  desc: null
  value:
    dir: ''
    reset_prediction_head: true
    freeze_main: false
run_multiple_splits:
  desc: null
  value: []
gt:
  desc: null
  value:
    layer_type: SANLayer
    layers: 3
    n_heads: 8
    dim_hidden: 64
    full_graph: true
    gamma: 1.0e-05
    pna_degrees: []
    dropout: 0.0
    attn_dropout: 0.0
    layer_norm: false
    batch_norm: true
    residual: true
    bigbird:
      attention_type: block_sparse
      chunk_size_feed_forward: 0
      is_decoder: false
      add_cross_attention: false
      hidden_act: relu
      max_position_embeddings: 128
      use_bias: false
      num_random_blocks: 3
      block_size: 3
      layer_norm_eps: 1.0e-06
wandb:
  desc: null
  value:
    use: true
    entity: kaidicao
    project: Google Runtime
    name: ''
run_dir:
  desc: null
  value: results_{source}_{search}_Sun_22_Oct_14_30/0
run_id:
  desc: null
  value: 0
params:
  desc: null
  value: 644756
